name: Webhook On Push

on:
  push:
    branches: [ master ]
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Webhook
      uses: joelwmale/webhook-action@master
      with:
        url: "https://webhook.votoe.hu/webhook.php"
